### ISSUE TITLE
عدم کارکرد صحیح در صورت وجود ویرگول، نقطه و ...

### ISSUE THREAD

**Issue by dehghani-mehdi** [mr-shady/halfspace#1]
مثلا برای این متن: __من خسته ام، نمی توانم__، فاصله بین __خسته__ و __ام__ باید به نیم فاصله تبدیل شود، اما به دلیل وجود ویرگول این اتفاق رخ نمی دهد.

**Comment by mr-shady** [comment]
این مشکل دقیقا کجا رخ داده؟ روی نسخه php؟ یا جاوااسکریپت یا داخل اکستنشن؟
چون من دقیقا همین متن شما رو کپی کردم و تست کردم همچین مشکلی ندیدم توی هر سه نسخه و حتی با متن‌های مشابه با همین شرایطی که گفتید متن رو درست اصلاح می‌کرد

**Comment by dehghani-mehdi** [comment]
احتمالا شما درست می گید، تست دقیقتری انجام میدم و اگر مشکل از سمت کدهای شما بود مجدد این تیکت رو باز میکنم و جزئیات رو اعلام میکنم.
